# Generated by Django 2.0.7 on 2020-02-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
